FE=['HTML','JAVASCRIPT','CSS','REACT JS']
BE=['PYTHON','JAVA','C','C++']
print(FE)
FE.append('ANGULAR JS')
FE.append('EXPRESS JS')
print(FE)
FE.insert(3,'BOOTSTRAP')
FE.insert(4,'TALEWIND')
print(FE)
FE.pop(6)
FE.pop(1)
print(FE)
FE.remove('REACT JS')
print(FE)
FE.reverse()
print(FE)
print(FE.index("CSS"))
FE.extend(BE)
print(FE)
FE.sort()
print(FE)
FE.count(6)
print(FE)