a=int(input("enter the integer value: "))
b=float(input("enter the float value: "))
d=input("enter the string: ")
print("before int conversion: ",a)
print("conversion of int to string: ",str(a))
print("conversion of int to float: ",float(a))
print("conversion of int to complex: ",complex(a))
print("before float conversion: ",b)
print("conversion of float to string: ",str(b))
print("conversion of float to int: ",int(b))
print("conversion of floatt to complex: ",complex(b))
print("before string conversion: ",d)
print("conversion of string to int: ",int(d))
print("conversion of string to float: ",float(d))
print("conversion of string to complex: ",list(d))
print("conversion of string to tuple: ",tuple(d))