str=input("enter the string: ")
print("user defined string: ",str)
print(str[::-1])
print(str.lower())
print(str.upper())
print(str.swapcase())
print(str.title())
print(str.capitalize())

print(str.startswith('p'))
print(str.endswith('ing'))
print(str.find('a'))
print(str.count('m'))
print(str.replace("p", "j"))
print(str.isdigit())

print(str.isnumeric())
print(str.isalpha())
print(str.isalnum())