tuple=(10,25.5,1+5j,'hello','we','are','learning','python',[10,20,30])
print(tuple)
#positive indexing
print("positive indexing")
print(tuple[0])
print(tuple[1])
print(tuple[2])
print(tuple[3])
print(tuple[4])
print(tuple[5])
print(tuple[6])
print(tuple[7])
print(tuple[8])
print("negative indexing:")
print(tuple[-9])
print(tuple[-8])
print(tuple[-7])
print(tuple[-6])
print(tuple[-5])
print(tuple[-4])
print(tuple[-3])
print(tuple[-2])
print(tuple[-1])